server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
<<<<<<< HEAD
            - Path=/api/product/**
        - id: inventory-service
          uri: http//localhost:8082
          predicates:
            - Path=/api/inventory/**
=======
            - Path=/api/products/**
        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**, /api/products/**

eureka:
instance:
  instance-id: "${spring.application.name}:${random.uuid}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
>>>>>>> feature/purchase-endpoint
